global:
    # How frequently to scrape targets by default.
    scrape_interval: 1m
    # How long until a scrape request times out.
    scrape_timeout: 10s
    # How frequently to evaluate rules.
    evaluation_interval: 1m

rule_files:
    - "/etc/prometheus/alert.rules"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
    - job_name: 'node-exporter'
      scrape_interval: 5s
      metrics_path: 'metrics'
      static_configs:
        - targets: ['nodeexporter:9100']
#    - job_name: 'docker'
#      scrape_interval: 5s
#      metrics_path: 'metrics'
#      static_configs:
#	target docker would display the metrics from docker itself. but i miss the ip from host.docker.internal
#        - targets: ['host.docker.internal:9323']
